vscode:
  extensions:
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - ecmel.vscode-html-css@0.2.3:RBTpzQbz8rn5KTlc82tnsQ==
    - mgmcdermott.vscode-language-babel@0.0.25:NtxlD2k9u9eAJSCbmUHSIA==